/* This file was generated by SableCC ( http://sablecc.org ). */

package language_mpire;

class NExpr_$1
    extends NExpr {

  private final int line;
  private final int pos;

  @Override
  public int getLine() {
    return this.line;
  }

  @Override
  public int getPos() {
    return this.pos;
  }

  @Override
  public String getText() {
    return null;
  }

  @Override
  public void apply(Walker walker) {
    walker.defaultIn(this);
    walker.defaultCase(this);
    walker.defaultOut(this);
  }

  @Override
  public void applyOnChildren(Walker walker) {
  }

  public NExpr_$1(int line, int pos) {
    this.line = line;
    this.pos = pos;
  }

  @Override
  public Type getType() {
    return Type.TAnonymous;
  }

  @Override
  public ProductionType getProductionType() {
    return ProductionType.T_Expr;
  }

  @Override
  InternalType getInternalType() {
    return InternalType.T_Expr_$1;
  }
}
